name: Generate GitHub Contributions Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clean dist directory
        run: |
          rm -rf dist/*  # Nettoie le répertoire dist avant de commencer

      - name: Generate GitHub Contributions Snake Animations
        uses: Platane/snk@v3.2.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}

      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.METRICS_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update snake animation [skip ci]"

      - name: Checkout Output Branch
        uses: actions/checkout@v4
        with:
          ref: output  # Checkout the output branch

      - name: Verify if github-snake.svg exists
        run: |
          if [ ! -f dist/github-snake.svg ]; then
            echo "Error: github-snake.svg not found"
            exit 1
          fi

      - name: Force remove problematic files
        run: |
          git rm -f dist/github-snake-dark.svg dist/github-snake.svg dist/ocean.gif || true  # Force delete problematic files

      - name: Copy github-snake.svg from output to main
        run: |
          mkdir -p dist
          cp dist/github-snake.svg dist/  # Copy to the same directory in the main branch
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/github-snake.svg
          git commit -m "Copy github-snake.svg from output branch"
          git push origin main  # Push to the main branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
