name: Generate GitHub Contributions Snake Animation

on:
  # Schedule the workflow to run daily at midnight UTC
  schedule:
    - cron: "0 0 * * *"

  # Allow manual triggering of the workflow
  workflow_dispatch:

  # Trigger the workflow on pushes to the main branch
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4


      # Step 2: Generate the snake animations
      - name: Generate GitHub Contributions Snake Animations
        uses: Platane/snk@v3.2.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}

      # STEP TEST
      - name: Fix permissions on files
        run: |
          chmod -R 777 dist
          ls -l dist  # Optionnel : Pour afficher les fichiers et vérifier leurs permissions

      # Step 3: Deploy the generated files to the 'output' branch
      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.METRICS_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update snake animation [skip ci]"

      # Step 4: Checkout the Output Branch
      - name: Checkout Output Branch
        uses: actions/checkout@v4
        with:
          ref: output  # Checkout the output branch

      # Step 5: Copy the snake.svg file from the output branch to the main branch
      - name: Verify if snake.svg exists
        run: |
          if [ ! -f dist/github-snake.svg ]; then
            echo "Error: snake.svg not found"
            exit 1
          fi

      - name: Copy snake.svg from output to main
        run: |
          mkdir -p dist
          cp dist/github-snake.svg dist/
          git config Sofiane.Wattiez "GitHub Actions"
          git config sofiane.wattiez.developpeur@gmail.com "github-actions[bot]@users.noreply.github.com"
          git add dist/github-snake.svg
          git commit -m "Copy snake.svg from output branch"
          git push origin main  # Push to the main branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}